apiVersion: v1
kind: Service
metadata: 
   labels:
     name: myfirstexternalloadbalancer
     tier: frontend
spec:
  type: Loadbalancer
  selector: 
    name: mywebapp
  ports:
    - port: 80
      targetPort: 3230

      