apiVersion: v1
kind: Service
metadata:
   name: myfirstloadbalancer
spec:
   type: Loadbalancer
   selector:
      name: mywebapp
   ports:
     - port: 80
       targetPort: 80
    
  

    
        
         


